name: MinecraftTransport
main: net.rezxis.mctp.client.MinecraftTransport
version: 1.1
description: Publish a server without opening ports.
authors: [Lunac, Cur]
website: https://nohit.cc/mctp
loadbefore: ["ProtocolLib"]
commands:
  checkip:
    description: A command to check reserved ip.